### ISSUE TITLE
Queried graph is not synced to Logseq

### ISSUE THREAD

**Issue by mtravers** [logseq/nbb-logseq#1]
I want to use nbb-logseq to do a dump of my graph which I then use as input to a static html publisher. This works well, except that the dumped graph is not up to date if Logseq is running. I need to quit Logseq, or force a re-index, if I want an uptodate graph.

I'm not sure if this is even something nbb-logseq can fix, it seems like I would need to send some kind of interprocess cmd to Logseq or something like that, but thought I'd ask. Thanks for any help.

Here's where I am calling nbb-logseq:
https://github.com/mtravers/goddinpotty/blob/nbb/src/goddinpotty/import/logseq.clj#L104

**Comment by logseq-cldwalker** [comment]
Hi. If your nbb-logseq script is using the cached graph, you're right that the dumped graph is not up to date. You can run the command `Save current graph to disk` to update the cached graph. Depending on how timely you need the results, running that command could be annoying.

Thankfully, the latest logseq has [the graph-parser library](https://github.com/logseq/logseq/tree/master/deps/graph-parser) which is nbb-logseq compatible and can parse your graph from source with `logseq.graph-parser.cli/parse-graph`. See https://github.com/logseq/logseq/blob/master/deps/graph-parser/test/logseq/graph_parser/cli_test.cljs for a test example and https://github.com/logseq/nbb-logseq/tree/main/examples/fly-io for a real world example

**Comment by logseq-cldwalker** [comment]
Hope that helps and will be curious to see what you end up building

**Comment by mtravers** [comment]
Thanks, that's very helpful!

My goal is to get the publishing process to one step, so I'm trying to avoid having to run commands in Logseq, but the Save current graph to disk is useful to know about.

And the graph-parser library looks like it will do what I need.

**Comment by logseq-cldwalker** [comment]
> My goal is to get the publishing process to one step

Fwiw, if you just want the logseq published app as a CI step, there is
https://github.com/pengx17/logseq-publish. If you want any kind of
customizability beyond what the Logseq app provides, then nbb-logseq is
definitely the way to go. Will be interested to see the resulting script if
you go the nbb-logseq route. Cheers

**Comment by logseq-cldwalker** [comment]
Closing as I think this is resolved but happy to reopen as needed
