### ISSUE TITLE
Can't run :where (property ...) query - Missing rules var '%' in :in

### ISSUE THREAD

**Issue by davclark** [logseq/nbb-logseq#2]
I'm trying to set up a more interactive approach to exploring logseq advanced / datomic queries, where I can look at the return values of the query directly without the extra layer of view logic in the Logseq app.

I've got a minimal "CV" repo set up [here](https://github.com/davclark/publishing-with-logseq/tree/5dd186b27f13076ebad0e95edc6385ff779a413a)

It's pretty straightforward to reproduce my error following the instructions in the README (which are probably overly detailed for anyone working on the main nbb-logseq repo). But in short, regular queries seem to work fine (e.g., those in the example directory README in this repo). But my attempts to do a property filtering by property fail with `Missing rules var '%' in :in`. E.g. specifically:

```
$ npx nbb-logseq query.cljs publishing-with-logseq '[:find (pull ?b [*]) :where (property ?b :type "job")]'
```

If you look at the graph in that repo in the Logseq app (just checked on latest beta, 0.7.8), the query DOES work and the various "job" blocks are displayed. For reference, that query is:

```
#+BEGIN_QUERY
{
:title [:h2 "Work Experience"]
:query [
    :find (pull ?b [*])
    :where 
        (property ?b :type "job")
]
}
#+END_QUERY
```

UPDATE: I had a look at how nbb-logseq is built and I didn't realize it was simply using generic libraries for transit and datascript. So, `(property)` needs to be defined. I'll see about implementing this as a one-off then continue the discussion about the best way to support logseq-specific datascript constructs.

**Comment by davclark** [comment]
I have searched a bit through the logseq codebase and I found these, which are apparently designed for use in nbb-logseq:

https://github.com/logseq/logseq/blob/master/deps/db/src/logseq/db/rules.cljc

I used those to manually convert my query to "vanilla" datalog, and so this works assuming you've ingested the above-linked graph / repo:

`npx nbb-logseq query.cljs publishing-with-logseq '[:find (pull ?b [*]) :where [?b :block/properties ?prop] [(get ?prop :type) ?type] [(= ?type "job")]]'`

It seems like there's logic for including rules in an :in clause in the main logseq codebase (particularly query_dsl.cljs), though there's enough of a pipeline of query re-writing that I'm getting a bit lost.

In any case, this has been a pretty useful dive into datalog for me, and on my own I'll spend a bit more time experimenting with rules and understanding how they work. I can probably hack together a solution that works well enough for my purposes.

BUT I also see that the "right" move is probably to somehow include the rules from the version of logseq that I'm actually using... this would allow the compiled version of the graph to change (along with the specifics of a rule like `property`). My guess is this is pretty simple for someone who actually knows the intended workings of nbb-logseq than I do.

**Comment by logseq-cldwalker** [comment]
Hi @davclark. Thanks for the repro. You are correct that you're missing rules from the `logseq.db.rules` ns. https://github.com/logseq/graph-validator/blob/6aeaabfb5c2ecf7781937380b6569ba04b3efdbd/action.cljs#L52-L56 is an example demonstrating using it. For more examples of using datascript rules, see [their tests](https://github.com/tonsky/datascript/blob/master/test/datascript/test/query_rules.cljc).

In order to require that ns into your script, you have to get into nbb's dependency management. There are two main approaches to pull in the the [logseq.db dependency](https://github.com/logseq/logseq/tree/master/deps/db):

1. Use https://github.com/babashka/babashka with [this tutorial](https://github.com/babashka/nbb/blob/51bf9dda0ee5392ce4b8f44054d6b8f4c5259ad4/doc/dependencies.md). Pull in the db dep as a gitdep.
2. Use yarn 3's ability to pull in a gitdep. https://github.com/logseq/graph-validator/ is setup to do this. You would need to copy .yarn/, .yarnrc.yml and package.json from that repo into your project and then `yarn install`. You would also need to tweak the test script in `package.json`.

I'd recommend doing step 2 unless you're familar enough with clojure and babashka.

The nbb dependency story is still tricky for beginner clojurists and hopefully https://github.com/babashka/nbb/issues/20 will make this smoother.

Happy to leave this issue open until you've been able to successfully try one of the above

**Comment by davclark** [comment]
I just wanted to provide an update since your response is over a week old - I'm in the midst of a job search, so I haven't dedicated a lot of time to meta-productivity projects like this.

In general, I'd like to get to the point where I could contribute to rough edges around nbb and logseq. It seems in this case, using (I guess?) @borkdude's recommended approach for installing nbb dependencies is going to be more likely to contribute something to nbb-logseq? Even if not, I'm inclined to lean that way, as I'm not much of a JS dev and I'd rather lean into Clojure tooling.

EDIT: And of course, thank you for the extensive reply! It's always a treat to interact with a helpful Clojurist.
EDIT 2: The nbb.edn approach was actually released in nbb 0.7.131 9 days ago, so I'll definitely use that.

**Comment by davclark** [comment]
I now have a working set of steps that make me want to help release a new version of nbb-logseq now :)

I've used vanilla nbb v0.7.131 to download the files from the logseq git repo using [nbb.edn](https://github.com/davclark/publishing-with-logseq/blob/15b2808b241114c1375f85f358b5c942c35501a4/nbb.edn). This downloads the dependencies when I run `nbb` (NOT `nbb-logseq`), and then you can do this in the REPL:

```
user=> (require '[logseq.db.rules :as rules])
nil
user=> (vals rules/query-dsl-rules)
([(all-page-tags ?p) [_ :block/tags ?p]] [(task ?b ?markers) [?b :block/marker ?marker] ... *AND SO ON*
```

To get it working in `nbb-logseq`, I implemented this [deps.cljs](https://github.com/davclark/publishing-with-logseq/blob/15b2808b241114c1375f85f358b5c942c35501a4/deps.cljs) file, which has the `*deps-hash*` hard-coded into the classpath.

I verified that the query script still runs, e.g.: `npx nbb-logseq query.cljs publishing-with-logseq '[:find (pull ?b [*]) :where [?b :block/properties ?prop] [(get ?prop :type) ?type] [(= ?type "job")]]'`, though I've not actually implemented *using* the rules as I'm already pushing well into evening time with my kiddo. But I see no reason why it wouldn't work... 🤞🏻 

But anyway, is there anyway I can help cut a new release based on the latest nbb? To be clear, I'm pretty sure I'm unstuck on this bit, it's just a funny manual process until the next release.

EDIT: I'm not 100% clear on how I should structure my nbb.edn - you'll see that I prefixed the dep like so: `logseq/logseq.db` (not sure it matters), and specified `:deps/root "deps/db"` in the dependency and I'm not sure that does anything useful. I welcome feedback on the canonical way to structure things.

EDIT 2: Can we replace nbb-logseq with a simpler nbb.edn deps solution now?

**Comment by davclark** [comment]
FWIW I've started mucking with copying your dependencies over to my repo in a [plain-nbb branch](https://github.com/davclark/publishing-with-logseq/tree/plain-nbb) to see if I can get the various features libs working. They do get downloaded now if I just run nbb - but e.g.:

```
❯ nbb query.cljs 
----- Error --------------------------------------
Message:  Could not find namespace: datascript.transit
```

**Comment by logseq-cldwalker** [comment]
Hi. Sorry to hear you're in the middle of a job search. nbb-logseq 0.7.133 now has the latest nbb.edn functionality. I've confirmed that your query.cljs works with it. There's an issue with passing files as arguments as described in https://github.com/babashka/nbb/issues/245 but I didn't encounter it with your `query.cljs`. Let me know when your query file works so we can resolve the issue.

As an aside, I saw you're looking at the `query-dsl` ns. Unfortunately anything out of logseq's `deps/` directory is unlikely to be nbb compatible as nbb can only handle a subset of cljs. If there are specific things you're trying to do with that `query-dsl`, feel free to share as that's helpful when prioritizing which namespaces to make nbb compatible

**Comment by davclark** [comment]
Thank you for leaving this issue running while I slowly mucked with this. I can confirm that the nbb-logseq 0.7.133 works for what I'm doing, but the way I'm doing things seems a little awkward with [this (into query' '[:in $ %]) operation](https://github.com/davclark/publishing-with-logseq/blob/34d0bff3ff17f90fe200d436987be7e44b0b0e04/query.cljs#L77). If I'm being obviously dumb, I welcome your input.

But most importantly it works!

**Comment by logseq-cldwalker** [comment]
Glad it works. That `into` is fine. You can also not do it but then you'd need to type that on the commandline every time you want to use a rule
