### ISSUE TITLE
Building nbb-logseq locally

### ISSUE THREAD

**Issue by Bad3r** [logseq/nbb-logseq#7]
Hello again :wave:,
I am having an issue compiling nbb-logseq locally.
The steps I followed are based on the CI build action.
```sh
❯ git clone git@github.com:logseq/nbb-logseq.git
❯ cd nbb-logseq
❯ bb npm-install
...
❯ NBB_CLI_NAME=nbb-logseq bb release   

up to date, audited 2 packages in 541ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Building with nbb env vars: {"NBB_CLI_NAME" "nbb-logseq"}
Building features: logseq/cljs-time, logseq/datascript, logseq/datascript-transit ...
[2023-04-05 21:31:16.087 - INFO] duplicate resource runners/karma.conf.js on classpath, using file:/.gitlibs/libs/reagent/reagent/315d702436719ea3a9a356773d6a10038ce9ea75/test/runners/karma.conf.js over jar:file:/.m2/repository/doo/doo/0.1.11/doo-0.1.11.jar!/runners/karma.conf.js
[:modules] Compiling ...
Wrote build report to: /git/nbb-logseq/report.html
[:modules] Build completed. (244 files, 0 compiled, 0 warnings, 25.90s)
NBB_CLI_NAME=nbb-logseq bb release  120.63s user 1.47s system 355% cpu 34.346 total
```

Everything seems to go well. The issue is that... I can't find the binary...
I looked everywhere, and the report.html file does not contain that information either.

[report.pdf](https://github.com/logseq/nbb-logseq/files/11165658/report.pdf)

I am sure its something evident. I would appreciate any help.

**Comment by Bad3r** [comment]
I see. You can't generate a binary but it can be added to other projects via yarn (https://github.com/logseq/nbb-logseq#qa-local-branch)

**Comment by Bad3r** [comment]
I guess my question is; can I build a binary of nbb-logseq that could be used anywhere?

**Comment by logseq-cldwalker** [comment]
Hi. You can install a global/binary version of nbb-logseq with `npm install @logseq/nbb-logseq -g`. If you'd like to build it yourself it, `yarn global add $PWD` after the build step

**Comment by Bad3r** [comment]
thank you `yarn global add $PWD` did the trick!
