### ISSUE TITLE
Cache graph parsing when using from Javascript

### ISSUE THREAD

**Issue by briansunter** [logseq/nbb-logseq#8]
Hello,
I'm wondering if there's a way to cache the graph loading and parsing when using from Javascript.
So I would be able to load the graph once, and perform multiple queries on it

https://github.com/logseq/nbb-logseq/tree/main/examples/from-js

const results = await loadString(`
  (ns query
    (:require [logseq.graph-parser.cli :as gp-cli]
              [logseq.db.rules :as rules]
              [datascript.core :as d]
              [clojure.edn :as edn]))

  (defn- main [graph-dir query*]
    (let [{:keys [conn]} (gp-cli/parse-graph graph-dir {:verbose false})
          query (into query* [:in '$ '%]) ;; assumes no :in are in queries
          results (map first (apply d/q query @conn [(vals rules/query-dsl-rules)]))]
      (clj->js results)))

  (main "${args[0]}" '${args[1]})
`);

**Comment by conn** [comment]
yeah, there's probably a way

**Comment by logseq-cldwalker** [comment]
Hi. The `@conn` in the script is your graph's database. Writing multiple queries in the .mjs is one way you could do this.

If you'd like to cache the database between script calls it's possible but will require you to use babashka and only clojurescript. Larger cached graphs like logseq's docs repo still take 1-2s to load. See https://github.com/logseq/bb-tasks#logseqbb-tasksnbbcached-db for more

Fwiw db graphs will not have this parsing step so this won't be an issue for them

**Comment by briansunter** [comment]
hey @logseq-cldwalker, I really appreciate the feedback. Doing multiple queries is definitely a good option, unfortunately in my case they depend on each other. From what you're saying, it sounds like it's not straightforward to cache the parsing across calls via Javascript. 

I considered doing the caching via nrepl, but seemed a bit too complex. 

https://github.com/babashka/nbb/blob/main/README.md#repl-api

If the new db doesn't require the parsing, seems like that would solve my problem, so I'll hold off for now and re-evaluate when the Logseq db version is further along.

Thanks!

**Comment by logseq-cldwalker** [comment]
Fwiw, most of the complexity around the caching link I sent is around incremental caching. If you're querying a graph that isn't changing often and don't mind a cache write taking 2-5s, the actual [cache read](https://github.com/logseq/bb-tasks/blob/70d3edeb287f5cec7192e642549a401f7d6d4263/src/logseq/bb_tasks/nbb/cached_db.cljs#L18) and [cache write](https://github.com/logseq/bb-tasks/blob/70d3edeb287f5cec7192e642549a401f7d6d4263/src/logseq/bb_tasks/nbb/cached_db.cljs#L46) are just dumb one-liners. But waiting for db version is also fine

**Comment by briansunter** [comment]
Ah, I might have misunderstood what you said earlier. I just got it working based on your suggestions in cache read and cache write. Just reading and writing the parsed db to a file via cljs, and calling that via loadFile or loadString in javascript

I just need fast queries for exporting, not writes, and querying from the cached file is quite fast.

Here's my quick solution, which is a mix of the from-js example and the bb-tasks cache loading, in case anyone else is trying to use this from Typescript.

https://gist.github.com/briansunter/b7843ada6b8460ba61dd32644d5ecbbe
